### ISSUE TITLE
crafting categories

### ISSUE THREAD

**Issue by Nexela** [AyrA/BasicKit#1]
While your way is valid the, the recommend way for .14 is to just nil crafting_categories
https://forums.factorio.com/viewtopic.php?f=7&t=31588#p201767

data.raw.player.player.crafting_categories = nil

**Comment by Nexela** [comment]
Actually close this I see what you did with the overrides now :)

**Comment by AyrA** [comment]
At the moment a recipe can only be in one category but I think they want to change that in the future and I just prepared for it, so when you create some sort of admin/god/creative item you would be screwed with this mod still on.

Apart from that, if you want some fun, do `data.raw.player.player.crafting_categories={""}`. It crashes the game but only when you open your inventory.
