### ISSUE TITLE
Not compatible with angel's mods.

### ISSUE THREAD

**Issue by credomane** [AyrA/BasicKit#2]
Or technically any other mod that adds items to the players inventory on player_create.

Angel's mods require a burner crusher which is added o the player inventory then cleared() by this mod. Making the game impossible before you even get started.

**Comment by AyrA** [comment]
If you want a quick solution you can open control.lua and remove these lines:

- L105-L107
- L116-L118

The first 3 lines prevent clearing the inventory and the next 3 prevent adding of the pickaxe.
Maybe I add options for this in the future. I think the factorio modding api is being changed (or has been) to allow for proper mod settings.

**Comment by AyrA** [comment]
Fixed as of [`v1.1.0`](/AyrA/BasicKit/releases/tag/v1.1.0)
