### ISSUE TITLE
Suggestion: Default "Don't clear Inventory" to Enabled

### ISSUE THREAD

**Issue by abordoli** [AyrA/BasicKit#3]
Working with another modder, Yas, whose vehicle won't appear unless this is enabled.

Regards,
~B

Would also like to chat with you...IRC or Discord?

**Comment by AyrA** [comment]
> Would also like to chat with you...IRC or Discord?

I use neither. You can [send me PMs on reddit](https://www.reddit.com/message/compose?to=%2Fu%2FAyrA_ch&subject=&message=) if you want to

**Comment by VasVadum** [comment]
Just wanted to leave a note, but your PM link didn't work, it appears that /u/ is refused and must be removed to send a message, but I'm not sure.  Reddit refused to send a PM to the link you gave.

**Comment by AyrA** [comment]
Fixed by latest release
